# Generated by Django 5.2.1 on 2025-05-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=255, unique=True)),
                ('BaseScore', models.DecimalField(decimal_places=1, max_digits=3)),
                ('BaseSeverity', models.CharField(max_length=8, unique=True)),
                ('ExploitabilityScore', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Exploitability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ІmpactScore', models.DecimalField(decimal_places=1, max_digits=3)),
                ('A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.a')),
                ('AC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.ac')),
                ('AV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.av')),
                ('C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.c')),
                ('I', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.i')),
                ('PR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.pr')),
                ('S', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.s')),
                ('UI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.ui')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.type')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.vendor')),
                ('Vulnerabilities', models.ManyToManyField(blank=True, to='vulnerabilities.vulnerability')),
            ],
        ),
    ]
