# Generated by Django 5.2.1 on 2025-06-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C',
            new_name='attack_complexity',
        ),
        migrations.RenameModel(
            old_name='PR',
            new_name='attack_vector',
        ),
        migrations.RenameModel(
            old_name='S',
            new_name='availability',
        ),
        migrations.RenameModel(
            old_name='AV',
            new_name='confidentiality',
        ),
        migrations.RenameModel(
            old_name='UI',
            new_name='integrity',
        ),
        migrations.RenameModel(
            old_name='I',
            new_name='privileges_required',
        ),
        migrations.RenameModel(
            old_name='AC',
            new_name='scope',
        ),
        migrations.RenameModel(
            old_name='A',
            new_name='user_interaction',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='C',
            new_name='attack_complexity',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='PR',
            new_name='attack_vector',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='S',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='AV',
            new_name='confidentiality',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='UI',
            new_name='integrity',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='I',
            new_name='privileges_required',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='AC',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='A',
            new_name='user_interaction',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='BaseSeverity',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Exploitability',
        ),
    ]
